using System.Linq;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Wega.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NanoChatJoinGroupPopup : DefaultWindow
{
    public Action<string>? OnGroupJoined;

    public NanoChatJoinGroupPopup()
    {
        RobustXamlLoader.Load(this);

        CancelButton.OnPressed += _ => Close();
        JoinButton.OnPressed += _ =>
        {
            if (!string.IsNullOrWhiteSpace(GroupIdInput.Text))
            {
                var normalizedId = NormalizeGroupId(GroupIdInput.Text.Trim());
                var groupId = normalizedId.Length <= 5
                    ? normalizedId
                    : normalizedId[..5];

                OnGroupJoined?.Invoke(groupId);
                Close();
            }
        };
    }

    private string NormalizeGroupId(string contactId)
    {
        var cleanedId = contactId.Trim().Replace(" ", "");
        if (!cleanedId.StartsWith("G") && cleanedId.All(char.IsDigit))
            return "G" + cleanedId;

        return cleanedId;
    }
}
