using Content.Shared.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface;

namespace Content.Client._Wega.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NanoChatContactControl : Control
{
    public Action? OnPressed;

    private readonly ChatContact _contact;

    public NanoChatContactControl(ChatContact contact)
    {
        RobustXamlLoader.Load(this);
        _contact = contact;

        var contactName = contact.ContactName;
        if (contact.HasUnread)
            contactName += Loc.GetString("nano-chat-ui-unread-indicator");
        ContactName.Text = contactName;

        MainButton.OnPressed += _ => OnPressed?.Invoke();
    }
}
