using Content.Shared.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface;

namespace Content.Client._Wega.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NanoChatGroupControl : Control
{
    public Action? OnPressed;

    private readonly ChatGroup _group;

    public NanoChatGroupControl(ChatGroup group)
    {
        RobustXamlLoader.Load(this);
        _group = group;

        var groupName = group.GroupName;
        if (group.HasUnread)
            groupName += Loc.GetString("nano-chat-ui-unread-indicator");

        GroupName.Text = groupName;
        MemberCount.Text = group.MemberCount.ToString();

        MainButton.OnPressed += _ => OnPressed?.Invoke();
    }
}
