using Content.Shared.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface;

namespace Content.Client._Wega.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NanoChatMessageControl : Control
{
    public NanoChatMessageControl(ChatMessage message)
    {
        RobustXamlLoader.Load(this);

        MessageText.Text = message.Message;
        SenderName.Text = message.SenderName;
        TimeLabel.Text = message.Timestamp.ToString(@"hh\:mm");

        // Style message based on sender
        if (message.IsOwnMessage)
        {
            MessageContainer.HorizontalAlignment = HAlignment.Right;
            HeaderContainer.HorizontalAlignment = HAlignment.Right;

            if (!message.Delivered)
            {
                MessageText.ModulateSelfOverride = Color.Red;
            }
        }
        else
        {
            MessageContainer.HorizontalAlignment = HAlignment.Left;
            HeaderContainer.HorizontalAlignment = HAlignment.Left;
        }
    }
}