using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Wega.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NanoChatCreateGroupPopup : DefaultWindow
{
    public Action<string>? OnGroupCreated;

    public NanoChatCreateGroupPopup()
    {
        RobustXamlLoader.Load(this);

        CancelButton.OnPressed += _ => Close();
        CreateButton.OnPressed += _ =>
        {
            if (!string.IsNullOrWhiteSpace(GroupNameInput.Text))
            {
                var groupName = GroupNameInput.Text.Length <= 16
                    ? GroupNameInput.Text
                    : GroupNameInput.Text[..16];

                OnGroupCreated?.Invoke(groupName);
                Close();
            }
        };
    }
}
