using System.Linq;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Wega.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NanoChatAddContactPopup : DefaultWindow
{
    public Action<string, string>? OnContactAdded;

    public NanoChatAddContactPopup()
    {
        RobustXamlLoader.Load(this);

        CancelButton.OnPressed += _ => Close();
        AddButton.OnPressed += _ =>
        {
            if (!string.IsNullOrWhiteSpace(ContactIdInput.Text) &&
                !string.IsNullOrWhiteSpace(ContactNameInput.Text))
            {
                var normalizedId = NormalizeContactId(ContactIdInput.Text);

                var contactId = normalizedId.Length <= 5
                    ? normalizedId
                    : normalizedId[..5];

                var contactName = ContactNameInput.Text.Length <= 9
                    ? ContactNameInput.Text
                    : ContactNameInput.Text[..9];

                OnContactAdded?.Invoke(contactId, contactName);
                Close();
            }
        };
    }

    private string NormalizeContactId(string contactId)
    {
        var cleanedId = contactId.Trim().Replace(" ", "");
        if (!cleanedId.StartsWith("#") && cleanedId.All(char.IsDigit))
            return "#" + cleanedId;

        return cleanedId;
    }
}
