using System.Linq;
using System.Numerics;
using Content.Client.Stylesheets;
using Content.Shared.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Wega.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NanoChatUiFragment : BoxContainer
{
    public Action? OpenAddContact;
    public Action? OnMutePressed;
    public Action? OpenEmojiPicker;
    public Action<string>? SetActiveChat;
    public Action<string>? SendMessage;
    public Action<string>? EraseChat;
    public Action<string>? CloseChat;

    private NanoChatEmojiPopup? _emojiPopup;

    public string? ActiveChatId;
    public Dictionary<string, ChatContact> Contacts = new();

    public NanoChatUiFragment()
    {
        RobustXamlLoader.Load(this);
        Orientation = LayoutOrientation.Vertical;

        AddContactButton.OnPressed += _ => OpenAddContact?.Invoke();
        MuteChatButton.OnPressed += _ => OnMutePressed?.Invoke();
        EmojiButton.OnPressed += _ => OpenEmojiPicker?.Invoke();

        SendButton.OnPressed += _ =>
        {
            if (ActiveChatId != null && !string.IsNullOrWhiteSpace(MessageInput.Text))
            {
                SendMessage?.Invoke(MessageInput.Text);
                MessageInput.Text = "";
            }
        };

        EraseChatButton.OnPressed += _ =>
        {
            if (ActiveChatId != null)
            {
                EraseChat?.Invoke(ActiveChatId);
                ActiveChatId = null;
            }
        };

        CloseChatButton.OnPressed += _ =>
        {
            if (ActiveChatId != null)
            {
                CloseChat?.Invoke(ActiveChatId);
                ActiveChatId = null;
                UpdateUiState();
            }
        };

        MessageInput.OnTextEntered += args =>
        {
            if (ActiveChatId != null && !string.IsNullOrWhiteSpace(args.Text))
            {
                SendMessage?.Invoke(args.Text);
                MessageInput.Text = "";
            }
        };

        EmojiButton.AddStyleClass(StyleNano.ButtonOpenBoth);
        SendButton.AddStyleClass(StyleNano.ButtonOpenLeft);

        UpdateUiState();
    }

    public void UpdateState(NanoChatUiState state)
    {
        OwnIdLabel.Text = state.ChatId;
        Contacts = state.Contacts;
        ActiveChatId = state.ActiveChat;

        MuteChatButton.TexturePath = state.Muted
            ? "/Textures/_Wega/Interface/soundoff.svg.192dpi"
            : "/Textures/_Wega/Interface/sound.svg.192dpi";
        MuteChatButton.ToolTip = state.Muted
            ? Loc.GetString("nano-chat-ui-unmute-tooltip")
            : Loc.GetString("nano-chat-ui-mute-tooltip");

        // Update contacts list
        UpdateContactsList();

        // Update messages if we have active chat
        if (state.ActiveChat != null && state.ActiveChatMessages != null)
        {
            UpdateMessages(state.ActiveChatMessages);
        }
        else
        {
            MessagesContainer.RemoveAllChildren();
        }

        UpdateUiState();
    }

    public void InitializeEmojiPicker()
    {
        _emojiPopup = new NanoChatEmojiPopup();
        _emojiPopup.OnEmojiSelected += emoji =>
        {
            if (ActiveChatId != null)
            {
                MessageInput.Text += emoji;
                MessageInput.CursorPosition = MessageInput.Text.Length;
            }
        };
    }

    public void OpenEmojiPickerInternal()
    {
        if (_emojiPopup == null)
            InitializeEmojiPicker();

        _emojiPopup?.OpenCentered();
    }

    private void UpdateContactsList()
    {
        ContactsContainer.RemoveAllChildren();
        NoContactsLabel.Visible = Contacts.Count == 0;

        foreach (var contact in Contacts.Values.OrderBy(c => c.ContactName))
        {
            var control = new NanoChatContactControl(contact);
            control.OnPressed += () => SetActiveChat?.Invoke(contact.ContactId);
            ContactsContainer.AddChild(control);
        }
    }

    private void UpdateMessages(List<ChatMessage> messages)
    {
        MessagesContainer.RemoveAllChildren();

        foreach (var message in messages)
        {
            var messageControl = new NanoChatMessageControl(message);
            MessagesContainer.AddChild(messageControl);

            // Add some spacing between messages
            MessagesContainer.AddChild(new Control { MinSize = new Vector2(0, 4) });
        }
    }

    private void UpdateUiState()
    {
        var hasActiveChat = ActiveChatId != null;

        // Update input state
        MessageInput.Editable = hasActiveChat;
        MessageInput.PlaceHolder = hasActiveChat
            ? Loc.GetString("nano-chat-ui-message-placeholder")
            : Loc.GetString("nano-chat-ui-select-chat-input");
        EmojiButton.Disabled = !hasActiveChat;
        SendButton.Disabled = !hasActiveChat;
        EraseChatButton.Visible = hasActiveChat;
        CloseChatButton.Visible = hasActiveChat;

        // Update chat title
        if (ActiveChatId != null && hasActiveChat && Contacts.TryGetValue(ActiveChatId, out var contact))
        {
            ChatTitle.Text = contact.ContactName;
        }
        else
        {
            ChatTitle.Text = Loc.GetString("nano-chat-ui-select-chat");
            MessagesContainer.RemoveAllChildren();
        }
    }
}
