using Content.Client.UserInterface.Controls;
using Content.Shared.Blood.Cult;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Player;

namespace Content.Client.Blood.Rites.UI;

[GenerateTypedNameReferences]
public sealed partial class BloodRitesMenu : RadialMenu
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IEntityNetworkManager _entityNetworkManager = default!;
    [Dependency] private readonly ISharedPlayerManager _playerManager = default!;

    public event Action<string>? OnSelectRites;
    public bool IsDisposed { get; private set; }

    public BloodRitesMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        InitializeButtons();
    }

    private void InitializeButtons()
    {
        BloodOrbButton.OnButtonUp += _ => HandleRitesSelection("ActionBloodCultOrb");
        BloodRechargeButton.OnButtonUp += _ => HandleRitesSelection("ActionBloodCultRecharge");
        BloodSpearButton.OnButtonUp += _ => HandleRitesSelection("ActionBloodCultSpear");
        BloodBoltBarrageButton.OnButtonUp += _ => HandleRitesSelection("ActionBloodCultBoltBarrage");
    }

    private void HandleRitesSelection(string ritesName)
    {
        OnSelectRites?.Invoke(ritesName);
        var netEntity = _entityManager.GetNetEntity(_playerManager.LocalSession?.AttachedEntity ?? EntityUid.Invalid);
        _entityNetworkManager.SendSystemNetworkMessage(new BloodRitesMenuClosedEvent(netEntity, ritesName));
        Close();
    }

    public new void Close()
    {
        if (!IsDisposed)
        {
            IsDisposed = true;
            Dispose();
        }
    }
}

