- type: department
  id: Cargo
  name: department-Cargo
  description: department-Cargo-description
  color: "#B48B57" # Corvax-Wega-Edit
  roles:
  - CargoTechnician
  - Quartermaster
  - SalvageSpecialist
  - Postman # Corvax-Wega-Postman

- type: department
  id: Civilian
  name: department-Civilian
  description: department-Civilian-description
  color: "#9FED58"
  weight: -10
  roles:
  - Bartender
  - Botanist
  - Boxer
  - Chaplain
  - Chef
  - Clown
  - HeadOfPersonnel
  - Janitor
  - Lawyer
  - Librarian
  - Mime
  - Musician
  - Passenger
  - Reporter
  - Visitor
  - Zookeeper
  - ServiceWorker
  - Barber # Corvax-Wega-Barber

- type: department
  id: CentralCommand
  name: department-CentralCommand
  description: department-CentralCommand-description
  color: "#2681A5" # Corvax-Wega-Edit
  roles:
  - CentralCommandOfficial
  - CBURN
  - ERTLeader
  - ERTChaplain
  - ERTJanitor
  - ERTMedical
  - ERTSecurity
  - ERTEngineer
  - DeathSquad
  editorHidden: true
  weight: 120

- type: department
  id: Command
  name: department-Command
  description: department-Command-description
  color: "#FCDF03" # Corvax-Wega-Edit
  roles:
  - Captain
  - IAA # Corvax-IAA
  - BlueShieldOfficer # Corvax-Wega-BlueShield
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfPersonnel
  - HeadOfSecurity
  - ResearchDirector
  - Quartermaster
  - CentralCommandOfficial
  - CBURN
  - ERTLeader
  - ERTChaplain
  - ERTJanitor
  - ERTMedical
  - ERTSecurity
  - ERTEngineer
  - DeathSquad
  primary: false
  weight: 100

- type: department
  id: Engineering
  name: department-Engineering
  description: department-Engineering-description
  color: "#FF733C" # Corvax-Wega-Edit
  roles:
  - AtmosphericTechnician
  - ChiefEngineer
  - SeniorEngineer # Corvax-MentorRoles
  - StationEngineer
  - TechnicalAssistant

- type: department
  id: Medical
  name: department-Medical
  description: department-Medical-description
  color: "#57B8F0" # Corvax-Wega-Edit
  roles:
  - Chemist
  - ChiefMedicalOfficer
  - Geneticist # Corvax-Wega-Genetics
  - Surgeon # Corvax-Wega-Surgery
  - Coroner # Corvax-Wega-Surgery
  - MedicalDoctor
  - MedicalIntern
  - Psychologist
  - Paramedic
  - SeniorPhysician # Corvax-MentorRoles

- type: department
  id: Security
  name: department-Security
  description: department-Security-description
  color: "#FF4242" # Corvax-Wega-Edit
  weight: 20
  roles:
  - HeadOfSecurity
  - SecurityCadet
  - SecurityOfficer
  - Brigmedic # Corvax-Wega-Brigmedic
  - SeniorOfficer # Corvax-MentorRoles
  - Pilot # Corvax-Pilot
  - Detective
  - Warden
  - WardenHelper # Corvax-Wega-WardenHelper

- type: department
  id: Science
  name: department-Science
  description: department-Science-description
  color: "#CD7CCD" # Corvax-Wega-Edit
  roles:
  - ResearchDirector
  - SeniorResearcher # Corvax-MentorRoles
  - Scientist
  - ResearchAssistant

- type: department
  id: Silicon
  name: department-Silicon
  description: department-Silicon-description
  color: "#D381C9"
  roles:
  - Borg
  - StationAi

- type: department
  id: Specific
  name: department-Specific
  description: department-Specific-description
  color: "#9FED58"
  weight: 10
  roles:
  - Boxer
  - Reporter
  - Zookeeper
  - Psychologist
  - Pilot # Corvax-Pilot
  - Barber # Corvax-Wega-Barber
  - Geneticist # Corvax-Wega-Genetics
  - Postman # Corvax-Wega-Postman
  primary: false
