using Content.Client.UserInterface.Controls;
using Content.Shared.Mining;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Wega.Mining;

[GenerateTypedNameReferences]
public sealed partial class MiningConsoleWindow : FancyWindow
{
    public Action? ToggleModePressed;
    public Action? ToggleActivationPressed;
    public Action? ToggleUpdateRequested;
    public Action? ToggleWithdrawPressed;
    public Action<NetEntity>? ToggleServerActivationPressed;
    public Action<NetEntity, int>? ServerStageChangePressed;

    public MiningConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ToggleMode.OnPressed += _ => ToggleModePressed?.Invoke();
        ToggleActivation.OnPressed += _ => ToggleActivationPressed?.Invoke();
        RefreshButton.OnPressed += _ => ToggleUpdateRequested?.Invoke();
        WithdrawButton.OnPressed += _ => ToggleWithdrawPressed?.Invoke();
    }

    public void UpdateState(MiningConsoleBoundInterfaceState state)
    {
        ModeLabel.Text = state.Mode.ToString();
        CreditsLabel.Text = $"{state.Credits:F0}";
        ResearchLabel.Text = $"{state.ResearchPoints:F0}";

        ToggleActivation.Text = state.GlobalActivation
            ? Loc.GetString("mining-console-deactivate-all")
            : Loc.GetString("mining-console-activate-all");

        ServersList.RemoveAllChildren();
        foreach (var server in state.Servers)
        {
            var control = new MiningServerControl(server);
            control.OnTogglePower += (serverUid) => ToggleServerActivationPressed?.Invoke(serverUid);
            control.OnStageChange += (serverUid, delta) => ServerStageChangePressed?.Invoke(serverUid, delta);
            ServersList.AddChild(control);
        }
    }
}
