- type: entity
  parent: BaseItem
  id: FlowerRose
  name: rose
  description: "Something beautiful."
  components:
  - type: Clothing
    slots:
    - HEAD
    quickEquip: false
  - type: Sprite
    sprite: _Wega/Objects/Specific/Hydroponics/rose.rsi
    state: produce
  - type: Produce
    seedId: rose
  - type: PotencyVisuals
  - type: Appearance
  - type: Tag
    tags:
    - Rose

- type: entity
  parent: BaseItem
  id: FlowerSunflower
  name: sunflower
  description: "Yellow is bright, like stars in space."
  components:
  - type: Clothing
    slots:
    - HEAD
    quickEquip: false
  - type: Sprite
    sprite: _Wega/Objects/Specific/Hydroponics/sunflower.rsi
    state: produce
  - type: Produce
    seedId: sunflower
  - type: PotencyVisuals
  - type: Appearance
  - type: Tag
    tags:
    - Sunflower

- type: entity
  parent: BaseItem
  id: FlowerPeaceFlower
  name: peaceflower
  description: "Something beautiful."
  components:
  - type: Clothing
    slots:
    - HEAD
    quickEquip: false
  - type: Sprite
    sprite: _Wega/Objects/Specific/Hydroponics/peaceflower.rsi
    state: produce
  - type: Tag
    tags:
    - Peaceflower

- type: entity
  parent: BaseItem
  id: FlowerClown
  name: clown flower
  description: "Something terrible."
  components:
  - type: Clothing
    slots:
    - HEAD
    quickEquip: false
  - type: Sprite
    sprite: _Wega/Objects/Specific/Hydroponics/clownflower.rsi
    state: produce
  - type: Produce
    seedId: clownflower
  - type: PotencyVisuals
  - type: Appearance

- type: entity
  name: money cabbage
  description: "Money, money, MONEY!!"
  id: FoodMoneyCabbage
  parent: ProduceBase
  components:
  - type: Sprite
    sprite: _Wega/Objects/Specific/Hydroponics/moneycabbage.rsi
  - type: SolutionContainerManager
    solutions:
      food:
        reagents:
        - ReagentId: Cellulose
          Quantity: 5
  - type: Item
    heldPrefix: produce
  - type: Produce
    seedId: moneyCabbage
  - type: SpawnItemsOnUse
    items:
      - type: entity
      - id: SpaceCash75
    sound:
      path: /Audio/Effects/unwrap.ogg

- type: entity
  name: demonic watermelon
  parent: [FoodProduceBase, ItemHeftyBase]
  id: FoodDemonicWatermelon
  description: "Who would have thought that the main symbol of evil would be a watermelon?"
  components:
  - type: Item
    size: Small
    heldPrefix: produce
  - type: FlavorProfile
    flavors:
      - demonicwatermelon
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 25
        reagents:
        - ReagentId: Nutriment
          Quantity: 10
        - ReagentId: Vitamin
          Quantity: 5
        - ReagentId: Unholywater
          Quantity: 10
  - type: Sprite
    sprite: _Wega/Objects/Specific/Hydroponics/demonicwatermelon.rsi
  - type: Produce
    seedId: demonicWatermelon
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: DemonsBlood
        Quantity: 20
  - type: Damageable
    damageContainer: Biological
  - type: DamageOnHighSpeedImpact
    minimumSpeed: 0.1
    damage:
      types:
        Blunt: 1
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 1
      behaviors:
      - !type:PlaySoundBehavior
        sound:
          collection: desecration
      - !type:SpillBehavior
        solution: food
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
  - type: SliceableFood
    count: 5
    slice: FoodDemonicWatermelonSlice
  - type: Butcherable
    butcheringType: Knife
    spawned:
    - id: ClothingHeadHatDemonicWatermelon
    - id: ClothingNeckWingsTail
  - type: Tag
    tags:
    - Fruit

- type: entity
  name: demonic watermelon slice
  parent: ProduceSliceBase
  id: FoodDemonicWatermelonSlice
  description: "A little piece of evil."
  components:
  - type: Item
    size: Tiny
  - type: FlavorProfile
    flavors:
      - demonicwatermelon
  - type: Sprite
    sprite: _Wega/Objects/Specific/Hydroponics/demonicwatermelon.rsi
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 5
        reagents:
        - ReagentId: Nutriment
          Quantity: 2
        - ReagentId: Vitamin
          Quantity: 1
        - ReagentId: Unholywater
          Quantity: 2
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: DemonsBlood
        Quantity: 4
  - type: Tag
    tags:
    - Fruit
    - Slice

- type: entity
  name: blue space banan
  parent: FoodProduceBase
  id: FoodBlueSpaceBanana
  description: "Weird blue banana"
  components:
  - type: Item
    heldPrefix: produce
  - type: FlavorProfile
    flavors:
      - banana
  - type: Food
    trash:
    - TrashBlueSpaceBananaPeel
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 6
        reagents:
        - ReagentId: Nutriment
          Quantity: 4
        - ReagentId: Vitamin
          Quantity: 2
  - type: Sprite
    sprite: _Wega/Objects/Specific/Hydroponics/blue_space_banana.rsi
  - type: Produce
    seedId: blueSpaceBanana
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: JuiceBanana
        Quantity: 10
  - type: Tag
    tags:
    - Fruit

- type: entity
  name: blue space banana peel
  parent: BaseItem
  id: TrashBlueSpaceBananaPeel
  description: "The pinnacle of the art of humor."
  components:
    - type: Sprite
      sprite: _Wega/Objects/Specific/Hydroponics/blue_space_banana.rsi
      state: peel
    - type: Item
      sprite: _Wega/Objects/Specific/Hydroponics/blue_space_banana.rsi
      heldPrefix: peel
    - type: Slippery
      slipSound:
        path: "/Audio/Effects/teleport_arrival.ogg"
        params:
          volume: -5
    - type: StepTrigger
      intersectRatio: 0.2
    - type: CollisionWake
      enabled: false
    - type: Physics
      bodyType: Dynamic
    - type: Fixtures
      fixtures:
        slips:
          shape:
            !type:PhysShapeAabb
            bounds: "-0.2,-0.2,0.2,0.2"
          hard: false
          layer:
          - SlipLayer
        fix1:
          shape:
            !type:PhysShapeAabb
            bounds: "-0.2,-0.2,0.2,0.2"
          density: 30
          mask:
          - ItemMask
    - type: Tag
      tags:
      - Recyclable
      - Trash
      - BananaPeel
    - type: SolutionContainerManager
      solutions:
        food:
          maxVol: 10
          reagents:
          - ReagentId: PulpedBananaPeel
            Quantity: 10
    - type: Extractable
      grindableSolutionName: food
    - type: SpaceGarbage
    - type: TriggerOnSlip
    - type: DeleteOnTrigger
    - type: SpawnOnTrigger
      proto: PortalBsBanan

- type: entity
  name: glowing berries
  parent: FoodProduceBase
  id: FoodRadioactiveBerries
  description: "They look so delicious! But for some reason it's hard to look at them."
  components:
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 7
        reagents:
        - ReagentId: Radium
          Quantity: 7
  - type: Sprite
    sprite: _Wega/Objects/Specific/Hydroponics/radioactive_berry.rsi
  - type: Produce
    seedId: radioactiveBerries
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: NuclearCola
        Quantity: 10
  - type: Tag
    tags:
    - Fruit
  - type: RadiationSource
    intensity: 0.2
    slope: 0.1
  - type: PointLight
    color: "#19FF19FF" 
    energy: 2.5
    radius: 1.5
    softness: 1

- type: entity
  name: alien berries
  parent: FoodProduceBase
  id: FoodAlienBerries
  description: "They look like very small pieces of alien artifacts."
  components:
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 5
        reagents:
        - ReagentId: Artifexium
          Quantity: 5
  - type: Sprite
    sprite: _Wega/Objects/Specific/Hydroponics/alien_berry.rsi
  - type: Produce
    seedId: alienBerries
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: Singulo
        Quantity: 10
  - type: Tag
    tags:
    - AlienBerries
    - Fruit

- type: entity
  name: energy potato
  parent: FoodProduceBase
  id: FoodEnergyPotato
  description: "Potatoes with a huge amount of nutrients!"
  components:
  - type: Item
    heldPrefix: produce
  - type: FlavorProfile
    flavors:
      - Potato
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 24
        reagents:
        - ReagentId: Nutriment
          Quantity: 9
        - ReagentId: Licoxide
          Quantity: 15
  - type: Sprite
    sprite: _Wega/Objects/Specific/Hydroponics/energy_potato.rsi
  - type: Produce
    seedId: energyPotato
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: JuicePotato
        Quantity: 20
  - type: Tag
    tags:
    - SuperPotato
    - Potato
    - Vegetable

- type: entity
  name: tea tree branch
  description: "The most aromatic part of this plant is not the leaves, but the branches!"
  id: BranchTreeTeaPlant
  parent: ProduceBase
  components:
  - type: Sprite
    sprite: _Wega/Objects/Specific/Hydroponics/relaxing_tea.rsi
  - type: SolutionContainerManager
    solutions:
      food:
        reagents:
        - ReagentId: RelaxingTeaAdust
          Quantity: 10
  - type: Produce
    seedId: treeTeaPlant

- type: entity
  name: invisible grapes
  parent: FoodProduceBase
  id: FoodInvisibleGrape
  description: "Barely noticeable grapes."
  components:
  - type: Item
    heldPrefix: produce
  - type: FlavorProfile
    flavors:
      - grape
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 4
        reagents:
        - ReagentId: GrapeJuiceInvisible
          Quantity: 2
        - ReagentId: Nothing
          Quantity: 2
  - type: Sprite
    sprite: _Wega/Objects/Specific/Hydroponics/Invisiblgrape.rsi
  - type: Produce
    seedId: invisibleGrape
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: GrapeJuiceInvisible
        Quantity: 5
  - type: Tag
    tags:
    - Fruit
